#pragma once
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by tools/extract_model_bounds.py
// Re-run this script when models are added or modified

#include <algorithm>
#include <string>
#include <unordered_map>

namespace mmo::config {

/// Bounding box dimensions extracted from GLB model files
struct ModelBounds {
    float min_x, min_y, min_z;
    float max_x, max_y, max_z;
    
    /// Width of the model (X axis)
    constexpr float width() const { return max_x - min_x; }
    
    /// Height of the model (Y axis - vertical in model space)
    constexpr float height() const { return max_y - min_y; }
    
    /// Depth of the model (Z axis)
    constexpr float depth() const { return max_z - min_z; }
    
    /// Maximum dimension (used for uniform scaling)
    float max_dimension() const { return std::max({width(), height(), depth()}); }
};

/// Get all model bounds extracted from GLB files
inline const std::unordered_map<std::string, ModelBounds>& get_all_model_bounds() {
    static const std::unordered_map<std::string, ModelBounds> bounds = {
        {"archer", {-0.181967f, -0.498991f, -0.397932f, 0.187021f, 0.498826f, 0.394043f}},
        {"building_blacksmith", {-0.500460f, -0.411024f, -0.500154f, 0.500421f, 0.433387f, 0.499813f}},
        {"building_house", {-0.498795f, -0.381449f, -0.494708f, 0.495659f, 0.477727f, 0.499990f}},
        {"building_shop", {-0.436159f, -0.373239f, -0.496179f, 0.443827f, 0.394210f, 0.500170f}},
        {"building_tavern", {-0.499498f, -0.481808f, -0.339270f, 0.498413f, 0.498925f, 0.357461f}},
        {"building_tower", {-0.245724f, -0.500893f, -0.247376f, 0.245818f, 0.501167f, 0.247514f}},
        {"building_well", {-0.401758f, -0.499046f, -0.354558f, 0.370140f, 0.499227f, 0.342328f}},
        {"ground_grass", {-0.500294f, -0.014243f, -0.500190f, 0.500266f, 0.013788f, 0.500755f}},
        {"ground_stone", {-0.500580f, -0.035779f, -0.501315f, 0.500356f, 0.038177f, 0.501256f}},
        {"inn", {-0.499423f, -0.398805f, -0.499505f, 0.462693f, 0.392729f, 0.496767f}},
        {"knight", {-0.410097f, -0.499976f, -0.500958f, 0.413341f, 0.500048f, 0.485655f}},
        {"log_tower", {-0.500082f, -0.402375f, -0.449574f, 0.500225f, 0.418495f, 0.468361f}},
        {"log_wall_1", {-0.499206f, -0.274027f, -0.475661f, 0.498913f, 0.277882f, 0.489167f}},
        {"log_wall_2", {-0.447875f, -0.379905f, -0.500184f, 0.461937f, 0.388257f, 0.500148f}},
        {"mage", {-0.435015f, -0.498499f, -0.307122f, 0.418077f, 0.498913f, 0.304181f}},
        {"mountain_large", {-0.438149f, -0.379296f, -0.500761f, 0.438043f, 0.387955f, 0.500598f}},
        {"mountain_medium", {-0.474474f, -0.450181f, -0.500493f, 0.469226f, 0.463715f, 0.500648f}},
        {"mountain_small", {-0.499690f, -0.452083f, -0.480307f, 0.499192f, 0.448409f, 0.475342f}},
        {"npc_blacksmith", {-0.497349f, -0.426255f, -0.305959f, 0.498857f, 0.415267f, 0.296675f}},
        {"npc_enemy", {-0.452359f, -0.433155f, -0.413309f, 0.500120f, 0.436428f, 0.417154f}},
        {"npc_guard", {-0.493654f, -0.500061f, -0.167934f, 0.470689f, 0.499908f, 0.166381f}},
        {"npc_innkeeper", {-0.449307f, -0.499825f, -0.321210f, 0.407675f, 0.499297f, 0.321230f}},
        {"npc_merchant", {-0.216755f, -0.500262f, -0.208276f, 0.216310f, 0.500375f, 0.210810f}},
        {"npc_villager", {-0.231613f, -0.499635f, -0.136186f, 0.224841f, 0.499778f, 0.138365f}},
        {"paladin", {-0.262827f, -0.500362f, -0.452974f, 0.358230f, 0.499651f, 0.472030f}},
        {"rock_boulder", {-0.432639f, -0.232663f, -0.500460f, 0.436242f, 0.226795f, 0.498618f}},
        {"rock_cluster", {-0.500920f, -0.257018f, -0.435819f, 0.499806f, 0.251386f, 0.436687f}},
        {"rock_mossy", {-0.386814f, -0.496986f, -0.383352f, 0.377753f, 0.497788f, 0.372276f}},
        {"rock_slate", {-0.497135f, -0.262967f, -0.496920f, 0.499038f, 0.268774f, 0.496874f}},
        {"rock_spire", {-0.272565f, -0.496294f, -0.235208f, 0.272941f, 0.499909f, 0.232584f}},
        {"spell_bible", {-0.500863f, -0.223632f, -0.386551f, 0.500929f, 0.231340f, 0.388658f}},
        {"spell_fireball", {-0.365933f, -0.499640f, -0.366109f, 0.365911f, 0.499712f, 0.365814f}},
        {"tree_dead", {-0.419324f, -0.455778f, -0.495590f, 0.414732f, 0.488789f, 0.479244f}},
        {"tree_oak", {-0.416530f, -0.500373f, -0.401104f, 0.416466f, 0.499708f, 0.381893f}},
        {"tree_pine", {-0.257044f, -0.500267f, -0.258072f, 0.264724f, 0.500553f, 0.259932f}},
        {"wall_corner", {-0.240653f, -0.500305f, -0.240327f, 0.240910f, 0.500973f, 0.259248f}},
        {"wall_gate", {-0.407024f, -0.500320f, -0.148892f, 0.407392f, 0.497036f, 0.149451f}},
        {"wall_segment", {-0.492923f, -0.164187f, -0.499740f, 0.498003f, 0.167866f, 0.484472f}},
        {"warrior", {-0.210541f, -0.499627f, -0.326799f, 0.209946f, 0.482054f, 0.316549f}},
        {"weapon_sword", {-0.500566f, -0.041878f, -0.101648f, 0.500271f, 0.040458f, 0.101472f}},
        {"wooden_log", {-0.132800f, -0.500065f, -0.025424f, 0.130868f, 0.499277f, 0.025563f}},
    };
    return bounds;
}

/// Get bounds for a specific model by name (returns nullptr if not found)
inline const ModelBounds* get_model_bounds(const std::string& model_name) {
    const auto& all_bounds = get_all_model_bounds();
    auto it = all_bounds.find(model_name);
    return it != all_bounds.end() ? &it->second : nullptr;
}

} // namespace mmo::config
